#!/bin/bash
# Quick script to start ngrok and get the URL

echo "🚀 Starting ngrok tunnel..."
echo ""
echo "Step 1: SSH to Raspberry Pi"
echo "Step 2: Start camera stream if not running"
echo "Step 3: Start ngrok"
echo ""
echo "Run these commands:"
echo "=================="
echo ""
echo "ssh admn@192.168.4.102"
echo ""
echo "# Start camera (if not running)"
echo "python3 camera_stream.py &"
echo ""
echo "# Start ngrok"
echo "ngrok http 8000"
echo ""
echo "=================="
echo ""
echo "After ngrok starts, you'll see:"
echo "  Forwarding  https://xxxx-xx-xx-xxx.ngrok-free.app -> http://localhost:8000"
echo ""
echo "Copy that HTTPS URL and use:"
echo "  railway variables set RASPBERRY_PI_URL=\"https://YOUR-URL.ngrok-free.app/stream.mjpg\""
echo ""

